#----------------------------------------------------------------------------------------------
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.
#----------------------------------------------------------------------------------------------

max = 4000000
x1 = 1
x2 = 2
# soma = x2 - o número 1 foi considerado ímpar por isso n entra na soma 
soma = 2

while (x2 < max):
    x = x1 + x2 
    if ( x%2 == 0 ):
     soma = soma + x
    else:
        soma = soma 
    x1 = x2
    x2 = x 

print(soma)
    